name: fc_security_web
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.5
  http: ^1.6.0
  socket_io_client: ^3.1.4
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  url_launcher: ^6.3.2
  intl: ^0.20.2
  # ✅ Version 5.x+ is highly recommended for stable Flutter Web camera support
  mobile_scanner: ^5.1.1 
  google_fonts: ^6.2.1
  
  # ✅ PDF and Printing dependencies for reports
  printing: ^5.11.1
  pdf: ^3.10.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

# Configuration for your Web Favicon and Android Icon
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  web:
    generate: true
    image_path: "assets/images/icon.png"
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true
  
  # ✅ Assets directory (if you have images)
  assets:
    - assets/images/